# 这里只写相对路径，不要写绝对路径
data:
  root_dir: "data"
  dxf_dir: "data/raw/dxf"
  raw_pickle_dir: "data/raw/pickle"
  raw_svg_dir: "data/raw/svg"
  dxf_extend_dir: "data/raw/dxf_extend"
  processed_svg_dir: "data/processed/svg"

model:
  save_dir: "models/checkpoints"

runtime:
  run_mode: "SINGLE"
  target_dir: "test"
  target_file: "南阳名门150.svg"
  output_dir: "output/exp_jsonld"
  sample_input_jsonld: "apartment_semantic_suites.jsonld"
  sample_output_jsonld: "apartment_semantic_suites_geo.json"
  sample_visualization_input: "北京保利140+135.jsonld"
  sample_visualization_output: "北京保利140+135.png"

llm:
  api_key: ""
  base_url: "https://open.bigmodel.cn/api/paas/v4/"
  model: "glm-4-flash"

output:
  gt_jsonld_dir: "output/gt_jsonld"
  html_dir: "output/html"
  exp_jsonld_dir: "output/exp_jsonld"
  svg_ins_dir: "output/svg_ins"
  cdt_dir: "output/cdt"
  exp_viz_dir: "output/exp_viz"
  gt_viz_dir: "output/gt_viz"
  exp_res_dir: "output/exp_res"
  gt_res_dir: "output/gt_res"

rules: "rules"

prompt:
  prompt_config_dir: "prompt/prompt_config.txt"